language: objective-c
osx_image: xcode8.3
env: TERM=dumb SHLVL=0
git:
  submodules: true
script:
  - "./platform-independent/cli-c/build"
  - "xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword iOS'"
  - "xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword macOS'"
