language: objective-c
osx_image: xcode8.3
env: TERM=dumb SHLVL=0
git:
  submodules: true
script:
  - "( brew install libsodium )"
  - "( cd ./platform-independent/cli-c && ./clean && ./build && ./mpw-tests )"
  - "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword iOS' -sdk iphonesimulator )"
  - "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword macOS' )"
